debug: true

build:
  image: hypriot/rpi-golang:1.5
  commands:
    - git clone --branch v2.0.0 https://github.com/coreos/go-etcd ${GOPATH}/src/github.com/coreos/go-etcd
    - export VERSION=v6
    - git clone -b ${VERSION} https://github.com/gliderlabs/registrator ${GOPATH}/src/github.com/gliderlabs/registrator
    - cd ${GOPATH}/src/github.com/gliderlabs/registrator
    - go get -d -v ./...
    - go build -ldflags "-X main.Version=${VERSION}" .
    - ls -la
    - pwd
    - find / -type f -name ".drone.yml"
    - ls -la /drone/src/github.com/
#    - cp registrator /drone/src


publish:
  docker:
#    environment:
#      - DOCKER_LAUNCH_DEBUG=true
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-registrator
    tag: v6

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: buildstatus
    username: Drone
    when:
      started: false
      success: true
      failure: true

